[package]
name = "aoc2019"
version = "0.1.0"
authors = ["smmalis37@gmail.com"]
edition = "2018"

[dependencies]
petgraph = "0.5.0"
paste = "0.1.7"
permutohedron = "0.2.4"
crossbeam = "0.7.3"
rayon = "1.3.0"
noisy_float = "0.1.12"
num-integer = "0.1.42"