[package]
name = "aoc2019"
version = "0.1.0"
authors = ["smmalis37@gmail.com"]
edition = "2018"

[dependencies]
arrayvec = "0.5.1"
petgraph = "0.4.13"
paste = "0.1.6"
permutohedron = "0.2.4"
crossbeam = "0.7.3"